name: Track MEGA Installers version number
on:
  workflow_dispatch:
  schedule:
    - cron: '6 * * * *'
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download MEGA Installers
        run: |
          $list = "MEGAsyncSetup32", "MEGAsyncSetup64", "MEGAcmdSetup32", "MEGAcmdSetup64"
          foreach ($installer in $list)
          {
            Invoke-WebRequest -Uri "https://mega.nz/$installer.exe" -OutFile "$installer.exe"
            Write-Output (Get-Item "$installer.exe").VersionInfo.ProductVersion > "$installer.txt"
          }
          Remove-Item *.exe

      - name: Commit and push changes
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add *.txt
          git commit -a -m "Update installer versions."
          git push origin
