name: Version Tracker
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download MEGA Installers
        run: |
          aria2c -i installers.txt
          list=("MEGAsyncSetup32" "MEGAsyncSetup64" "MEGAcmdSetup32" "MEGAcmdSetup64")
          for installer in "${list[@]}"
          do
             7z l ${installer}.exe | grep ProductVersion | grep -P -o -e "\d.+" > ${installer}.txt
          done
          rm -rf *.exe
      - name: Commit and push changes
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add *.txt
          git commit -a -m "Update installer versions."
          git push origin
