# This is a basic workflow to help you get started with Actions

name: Update MEGAsync version number

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Download MEGAsync installer
        run: Invoke-WebRequest -Uri "https://mega.nz/MEGAsyncSetup64.exe" -OutFile "latest.exe"

      # Runs a set of commands using the runners shell
      - name: Update version.txt
        run: Write-Output (Get-Item "latest.exe").VersionInfo.ProductVersion > version.txt
        
      - name: Commit and push changes
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add version.txt
          git commit -a -m "Update version.txt"
          git push origin
